EZChat App/EZChat App/EZChat App/Controllers/SignUpController.cs
using EZChat_App.App_Start;
using EZChat_App.Models;
using MongoDB.Driver.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EZChat_App.Controllers
{
    public class SignUpController : Controller
    {
        MongoContext _dbContext;
        // GET: SignUp
        public ActionResult Index()
        {
            _dbContext = new MongoContext();
            Users user = new Users();
            //Chargement des pays pour la dropdown
            List<Countries> countriesList = _dbContext.database.GetCollection<Countries>("Countries").FindAll().ToList();
            List<Lang> langList = _dbContext.database.GetCollection<Lang>("Lang").FindAll().ToList();
            ViewData["CountriesList"] = countriesList;
            ViewData["SpokenLang"] = langList;

            return View(user);
        }

        /// <summary>
        /// Register a user
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        public JsonResult Register(Users user)
        {
            try
            {
                //Intilalisation des données vides
                _dbContext = new MongoContext();
                user.FriendsListId = new MongoDB.Bson.BsonArray();
                user.PendingFriendsRequest = new MongoDB.Bson.BsonArray();
                user.PictureProfile = "";
                user.RegisterDate = DateTime.Now.ToString();

                _dbContext.database.GetCollection<Users>("users").Insert<Users>(user);
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch(Exception e)
            {
                e.GetBaseException();
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Connect()
        {

            return View();
        }

        public JsonResult Connexion(string username, string password)
        {
            if(string.IsNullOrEmpty(username) || string.IsNullOrEmpty(password))
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                _dbContext = new MongoContext();
                //Vérification pour savoir si l'utilisateur existe, si il existe on stocke en session.
                //+ Redirection vers le profile
                //Sinon message d'erreur + reste sur la page de connexion
                var query = Query.EQ("UserName", username);
                Users userConnect = _dbContext.database.GetCollection<Users>("users").FindOne(query);

                if(userConnect != null)
                {
                    if(userConnect.UserName == username && userConnect.Password == password)
                    {
                        _dbContext.database.GetCollection<Users>("users").Update(Query.EQ("_id", userConnect._id), Update.Set("ConnectionStatus", true));
                        Session["User"] = userConnect;
                        return Json(true, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            return Json(false, JsonRequestBehavior.AllowGet);
        }



    }
}

EZChat App/EZChat App/EZChat App/Controllers/UsersController.cs
using EZChat_App.App_Start;
using EZChat_App.Models;
using MongoDB.Driver;
using MongoDB.Driver.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EZChat_App.Controllers
{
    public class UsersController : Controller
    {
        MongoContext _dbContext;
        // GET: Modifier profile
        public ActionResult Index()
        {
            _dbContext = new MongoContext();
            var user = Session["User"];
            ViewData["CountriesList"] = _dbContext.database.GetCollection<Countries>("Countries").FindAll().ToList();
            ViewData["SpokenLang"] = _dbContext.database.GetCollection<Lang>("Lang").FindAll().ToList();
            return View(user);
        }

        public ActionResult SearchFriends()
        {
            return View();
        }

        /// <summary>
        /// Mise à jour de l'utilisateur
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        public JsonResult UpdateUser(Users user)
        {
            _dbContext = new MongoContext();
            Users UserToEdit = Session["User"] as Users;
            try
            {
                _dbContext.database.GetCollection<Users>("users").FindAndModify(
                                Query.EQ("_id", UserToEdit._id),
                                null,
                                Update.Set("UserName", user.UserName)
                                .Set("FirstName", user.FirstName)
                                .Set("LastName", user.LastName)
                                .Set("CountryCode", user.CountryCode)
                                .Set("LanguageCode", user.LanguageCode)
                                .Set("PictureProfile", user.PictureProfile == null ? "" : user.PictureProfile)
                                .Set("Email", user.Email)
                                .Set("BirthDate", user.BirthDate),
                                true);

                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch(Exception e)
            {
                e.GetBaseException();
                return Json(false, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

EZChat App/EZChat App/EZChat App/Views/SignUp/Connect.cshtml
@section head{
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")
}

<!------ Include the above in your HEAD tag ---------->
<div class="container">
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-title">Sign In</div>
                <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot password?</a></div>
            </div>
            <div style="padding-top:30px" class="panel-body">
                <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

                <form id="loginform" class="form-horizontal" role="form">

                    <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input id="login-username" type="text" class="form-control" name="username" value="" placeholder="Pseudo">
                    </div>

                    <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input id="login-password" type="password" class="form-control" name="password" placeholder="Mot de passe">
                    </div>

                  
                    <div style="margin-top:10px" class="form-group">
                        <!-- Button -->
                        <div class="col-sm-12 controls">
                            <a id="btn-login" href="#" class="btn btn-success">Connexion  </a>
                            <a id="btn-fblogin" href="#" class="btn btn-primary">Connexion avec Facebook</a>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12 control">
                            <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%">
                                Vous n'avez pas de compte ?
                                <a href="@Url.Action("Index","Signup")">
                                    Inscrivez-vous ici !
                                </a>
                            </div>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
@section scripts{
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
<script type="text/javascript">


    $(document).ready(function () {

        $("#btn-login").on("click", function () {
            CheckCredentials();
        });





    });

    function CheckCredentials() {

        var username = $("input[name='username']").val();
        var pass = $("input[name='password']").val();

        $.post("@Url.Action("Connexion","Signup")/" + "?username=" + username + "&password=" + pass).done(function (data) {
            window.location.href = '@Url.Action("Index","Users")';
        });

    }



</script>    
    
}

EZChat App/EZChat App/EZChat App/Views/SignUp/Index.cshtml
@model EZChat_App.Models.Users

@section head{
@Styles.Render("~/Content/css")
@Scripts.Render("~/bundles/modernizr")
<!------ Include the above in your HEAD tag ---------->
}

<div class="container"><br />
    <div class="row">
        <div id="profile" class="col-md-8 col-md-offset-2">
                <h5 class="text-center">Inscription</h5>
                <fieldset>
                    <legend>Création du compte utilisateur</legend>
                    <div class="form-group col-md-6">
                        <label for="UserName">Pseudo</label>
                        <input type="text" class="form-control" name="UserName" id="@Model.UserName" placeholder="">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="FirstName">Prénom</label>
                        <input type="text" class="form-control" name="FirstName" id="@Model.FirstName" placeholder="">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="LastName">Nom de famille</label>
                        <input type="text" class="form-control" name="LastName" id="@Model.LastName" placeholder="">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="">Email</label>
                        <input type="email" class="form-control" name="Email" id="@Model.Email" placeholder="@Model.Email">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="Password">Mot de passe</label>
                        <input type="password" class="form-control" name="Password" id="@Model.Password" placeholder="@Model.Password">
                    </div>

                </fieldset>
                <fieldset>
                    <legend>Détails</legend>
                    <div class="form-group col-md-6">
                        <label> Pays de résidence</label>
                        @Html.DropDownList("CountryCode",
                        new SelectList((System.Collections.IEnumerable)ViewData["CountriesList"], "code", "name"))
                    </div>
                    <div class="form-group col-md-6">
                        <label>Langue parlée</label>
                        @Html.DropDownList("LanguageCode",
                        new SelectList((System.Collections.IEnumerable)ViewData["SpokenLang"], "code", "name"))
                    </div>
                    <div class="form-group col-md-6">
                        <label for="BirthDate">Date de naissance</label>
                        <input type="date" name="BirthDate" />
                    </div>
                    <div class="form-group col-md-12 hidden">
                        <label for="specify">Veuillez spécifier ce champ</label>
                        <textarea class="form-control" id="specify" name=""></textarea>
                    </div>
                </fieldset>
                <div class="form-group">
                    <div class="col-md-12">
                        <button type="button" id="SignupBtn" class="btn btn-dark">Inscription</button>
                        <a href="@Url.Action("Connect","Signup")">Vous avez déjà un compte ?</a>
                    </div>
                </div>
        </div>
    </div>
</div>

@section scripts{

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")


    <script type="text/javascript">
        $(document).ready(function () {
            $('input').on('change', function () {
                $(this).val() == "" ? $('#specify').closest('.form-group').show() : $('#specify').closest('.form-group').hide();
            });

            $("#SignupBtn").on("click", function () {
                PostDetails();
            });






        });

        function PostDetails() {

            var details = $("#profile :input").serialize();
            $.post('@Url.Action("Register","SignUp")', details).done(function (data) {
                 window.location.href = '@Url.Action("Connect","SignUp")';
            });


        }

    </script>
    
}